"""add booking and room date inventory tables

Revision ID: 0278361a98f4
Revises: d5473ff0434d
Create Date: 2026-02-17 19:30:51.590250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0278361a98f4'
down_revision: Union[str, Sequence[str], None] = 'd5473ff0434d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("guest_id", sa.Integer(), nullable=False),
        sa.Column("room_type_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("check_in", sa.Date(), nullable=False),
        sa.Column("check_out", sa.Date(), nullable=False),
        sa.Column("num_rooms", sa.Integer(), nullable=False),
        sa.Column("num_guests", sa.Integer(), nullable=False),
        sa.Column("night_count", sa.Integer(), nullable=False),
        sa.Column("price_per_night", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("special_requests", sa.Text(), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["guest_id"], ["guests.id"]),
        sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"]),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"]),
        sa.ForeignKeyConstraint(["room_type_id"], ["room_types.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f('ix_bookings_guest_id'), 'bookings', ['guest_id'], unique=False)
    op.create_index(op.f('ix_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_bookings_location_id'), 'bookings', ['location_id'], unique=False)
    op.create_index(op.f('ix_bookings_room_type_id'), 'bookings', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_bookings_slug'), 'bookings', ['slug'], unique=True)
    op.create_table(
        "room_date_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("room_type_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_rooms", sa.Integer(), nullable=False),
        sa.Column("booked_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["room_type_id"], ["room_types.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "room_type_id",
            "date",
            name="uq_room_date_inventory_room_type_date",
        ),
    )
    op.create_index(
        "ix_room_date_inventory_room_type_date",
        "room_date_inventory",
        ["room_type_id", "date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_room_date_inventory_room_type_id"),
        "room_date_inventory",
        ["room_type_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_room_date_inventory_room_type_id"),
        table_name="room_date_inventory",
    )
    op.drop_index(
        "ix_room_date_inventory_room_type_date",
        table_name="room_date_inventory",
    )
    op.drop_table("room_date_inventory")
    op.drop_index(op.f("ix_bookings_slug"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_room_type_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_location_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_hotel_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_guest_id"), table_name="bookings")
    op.drop_table("bookings")
    # ### end Alembic commands ###
