"""add deleted_at to guests table

Revision ID: 12429c1a6629
Revises: bb4394f87ff4
Create Date: 2026-01-31 13:27:06.728443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12429c1a6629'
down_revision: Union[str, Sequence[str], None] = 'bb4394f87ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('guests', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('guests', 'deleted_at')
    # ### end Alembic commands ###
