"""create location_images table

Revision ID: d5473ff0434d
Revises: edd7ceca5f68
Create Date: 2026-02-15 00:05:03.921824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5473ff0434d'
down_revision: Union[str, Sequence[str], None] = 'edd7ceca5f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(255), nullable=False),
    sa.Column('file_path', sa.String(512), nullable=False),
    sa.Column('alt_text', sa.String(255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_images_location_id'), 'location_images', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_images_location_id'), table_name='location_images')
    op.drop_table('location_images')
    # ### end Alembic commands ###
