"""create room_types table

Revision ID: edd7ceca5f68
Revises: 12429c1a6629
Create Date: 2026-02-03 20:41:15.853023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Use sa.String for string columns (replaces sqlmodel.sql.sqltypes.AutoString)
# revision identifiers, used by Alembic.
revision: str = 'edd7ceca5f68'
down_revision: Union[str, Sequence[str], None] = '12429c1a6629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_inventory', sa.Integer(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('default_min_stay', sa.Integer(), nullable=False),
    sa.Column('max_advance_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_room_types_hotel_id'), 'room_types', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_room_types_location_id'), 'room_types', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_types_location_id'), table_name='room_types')
    op.drop_index(op.f('ix_room_types_hotel_id'), table_name='room_types')
    op.drop_table('room_types')
    # ### end Alembic commands ###
